name: Ads Not Collected Report
description: Report an that is hidden but not collected on AdNauseam.
body:
  - type: markdown
    attributes:
      value: |
        Please keep in mind that visible ads in websites such as YouTube, Facebook, Instagram change so often their structure that it is not realistic that we keep updating our parsers specifically for them.
  - type: checkboxes
    attributes:
      label: What type of Ad is not being collected
      options:
        - label: Image
          required: false
        - label: Text
          required: false
        - label: Video 
          required: false
        - label: Mid-roll Video Ad 
          required: false
        - label: Popup
          required: false
  - type: textarea
    attributes:
      label: URL(s) where the ads appear.
      description: |
        At least one URL is **MANDATORY** for an issue affecting a web page.
        The backticks (`) surrounding the URL(s) are important, it prevents the URL(s) from being clickable. Warn with **"NSFW"** where applicable.
      placeholder: |
        `https://example.com`
        `https://example.org`
        `https://example.net`
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot(s) of un-collected ads (disable AdNauseam if they are being correctly hidden by AdNauseam)
      description: |
        Screenshot(s) are **MANDATORY** for hard-to-describe visual issues.
        Post **LINKS** instead of inline images for screenshots containing **ADULT MATERIAL**.
    validations:
      required: true
