blank_issues_enabled: true
contact_links:
  - name: Discussion Forum
    url: https://github.com/dhowe/AdNauseam/discussions
    about: For questions, suggestion, please open a new discussion, or check the existing ones to avoid repeated ones.
  - name: Filter List Issues
    url: https://github.com/uBlockOrigin/uAssets/issues
    about: Strictly for **NON-ADNAUSEAM-SPECIFIC**